#!/usr/bin/env python3
"""
Generate docs/shortcuts.json and docs/keybank.js from one definition of the key bank.

Why a bank: the add-in-only manifest fixes shortcuts at load time, and this PowerPoint
build lacks KeyboardShortcuts 1.1 (no runtime replaceShortcuts). So we register every
key we might ever want up front as a generic "slot", and a keymap stored in the add-in
decides which command each slot runs. Assigning a key never needs a redeploy.

Bank = {Ctrl+Shift+Alt, Ctrl+Alt} x {A-Z, 0-9}. Both modifier sets are clear of every
documented PowerPoint-for-Mac shortcut and of macOS defaults. (Cmd-based sets are not
used: PowerPoint owns Cmd+Opt+Shift+B/F/G/C/V and macOS owns several Cmd+Opt combos.)

Run after editing MODIFIER_SETS or KEYS, then bump ?v= on ExtendedOverrides in manifest.xml.
"""
import json
import os

MODIFIER_SETS = ["Ctrl+Shift+Alt", "Ctrl+Alt"]
KEYS = [chr(c) for c in range(ord("A"), ord("Z") + 1)] + [str(d) for d in range(10)]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")


def slot_id(combo):
    return "k_" + combo.replace("+", "_")


def main():
    bank = [f"{mods}+{key}" for mods in MODIFIER_SETS for key in KEYS]

    shortcuts = {
        "actions": [
            {"id": slot_id(c), "type": "ExecuteFunction", "name": f"ChristiantialElements {c}"}
            for c in bank
        ],
        "shortcuts": [
            {"action": slot_id(c), "key": {"default": c, "mac": c}} for c in bank
        ],
    }
    with open(os.path.join(DOCS, "shortcuts.json"), "w") as f:
        json.dump(shortcuts, f, indent=2)
        f.write("\n")

    keybank_js = (
        "// GENERATED by scripts/build-shortcuts.py — do not edit. Must match docs/shortcuts.json.\n"
        "// Every combo here is registered with Office as action id slotId(combo).\n"
        "const KEY_BANK = " + json.dumps(bank) + ";\n"
        "const KEY_BANK_MODIFIER_SETS = " + json.dumps(MODIFIER_SETS) + ";\n"
        "const KEY_BANK_KEYS = " + json.dumps(KEYS) + ";\n"
        'function slotId(combo) { return "k_" + combo.replace(/\\+/g, "_"); }\n'
    )
    with open(os.path.join(DOCS, "keybank.js"), "w") as f:
        f.write(keybank_js)

    print(f"wrote {len(bank)} slots to docs/shortcuts.json and docs/keybank.js")


if __name__ == "__main__":
    main()
